[tool.ruff]
target-version = "py312"
select = ["E", "F", "I", "UP"]
ignore = ["D203"]
show-source = true

[tool.black]
target-version = ["py312"]

[tool.pylint.messages_control]
disable = "C0114,C0115,C0116"

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = ["tests"]
pythonpath = ['.']
